name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'  # укажите версию Qt, которую вы хотите использовать
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '$HOME/Qt'
          modules: 'qtbase,qttools,qtwidgets,qtnetwork'

      - name: Set up Qt environment
        run: echo "$HOME/Qt/5.15.2/gcc_64/bin" >> $GITHUB_PATH

      - name: Build Client
        run: |
          mkdir -p build
          cd build
          qmake ../client.pro
          make

      - name: Build Tests
        run: |
          mkdir -p build_test
          cd build_test
          qmake ../test_client.pro
          make

      - name: Run Tests
        run: |
          cd build_test
          ./ClientTest
